version: "3.8"

services:
  postgres:
    container_name: taskdb
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  api:
    container_name: api-task-manager
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 5005:5005
    env_file:
      - ./api/.env
    restart: "always"
    depends_on:
      - postgres
