version: '3.8'

services:

  todo-app-server:
    build: .
    ports:
      - "5005:5005"
    environment:
      MONGODB_URI: 'mongodb://db:27017/todo-app'
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - "27018:27017"