# fly.toml app configuration file generated for todo-ts-app-server on 2023-11-13T15:50:53+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "todo-ts-app-server"
primary_region = "mad"

[build]

[http_service]
  internal_port = 5005
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
