name: Testing & Fly Deploy
on:
  push:
    branches:
      - main

jobs:
  test:
    name: todo-ts-testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t todo-app-server .

      - name: Run Tests in Docker Container
        run: docker run todo-app-server npm test

  deploy:
    name: todo-ts-app-server
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
