name: Fly ci/cd
on:
  push:
    branches:
      - main
jobs:
  test:
    name: todo-ts-testing
    runs-on: ubuntu-latest

  steps:
    - name: Checkout code
    - uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get -y install docker.io
      if: runner.os == 'Linux'

    - name: Build Docker image
      run: docker build -t todo-app-server.

    - name: Run Tests in Docker Container
      run: docker run todo-app-server npm test

  deploy:
    name: todo-ts-app-server
    runs-on: ubuntu-latest
    needs: todo-ts-testing
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        